### ISSUE TITLE
Immediate crash

### ISSUE THREAD

**Issue by gonmf** [jmoudrik/frisbee-twogtp#1]
Hi, the program crashes immediatly at the start. It vomits::

```
B << 'list_commands'
Traceback (most recent call last):
  File "frisbee-twogtp.py", line 255, in <module>
    main()
  File "frisbee-twogtp.py", line 162, in main
    black = GtpBot(args.black_cmd, 'B')
  File "frisbee-twogtp.py", line 45, in __init__
    success, response = self.interact('list_commands')
  File "frisbee-twogtp.py", line 73, in interact
    self.write(gtp_cmd)
  File "frisbee-twogtp.py", line 62, in write
Logging to file matilda.log enabled
    self.p.stdin.write(bytes(gtp_cmd + "\n", 'ascii'))
warning: final_score estimation disabled
TypeError: str() takes at most 1 argument (2 given)
```

My program works with the gomill twogtp, so it should be okay in that end. Does it work on your end?

Cheers,
Gonçalo

**Comment by jmoudrik** [comment]
Hmm, do you run the code with python3? What version? I get the same error
if I run it using python2, so this might be the cause.

So you let the program decide the final location where the stone lands? And
what about the involuntary passes / (skips)?

Regards,
Josef

Dne so 16. 4. 2016 17:15 uživatel Gonçalo notifications@github.com napsal:

**Comment by gonmf** [comment]
It is python 2.7.9 yes. Now I can't seem to install gomill for python 3,
probably because of having multiple versions installed. Sigh.

Other than that yes my program implements the GTP commands you mentioned
in the mailing list.
